### Loading Files

In [39]:
import pandas as pd

home_df = pd.read_csv('home_page_table.csv')
search_df = pd.read_csv('search_page_table.csv')
payment_df = pd.read_csv('payment_page_table.csv')
confirmation_df = pd.read_csv('payment_confirmation_table.csv')
user_df = pd.read_csv('user_table.csv')

print("File loaded successfully.")

File loaded successfully.

### Cleaning

In [40]:
dataframes = [home_df, search_df, payment_df, confirmation_df, user_df]

for df in dataframes:
    df.columns = df.columns.str.strip().str.lower()
    
    if 'page' in df.columns:
        df['page'] = df['page'].str.strip().str.lower()

    df['user_id'] = df['user_id'].astype(int)

#Remove duplicates only from the user table
user_df = user_df.drop_duplicates(subset='user_id')

print("Data cleaned successfully.")

Data cleaned successfully.

Preview first, before exporting them.

In [41]:
from IPython.display import display

display(home_df.head())
display(search_df.head())
display(payment_df.head())
display(confirmation_df.head())
display(user_df.head())

   user_id       page
0   313593  home_page
1   468315  home_page
2   264005  home_page
3   290784  home_page
4   639104  home_page

   user_id         page
0    15866  search_page
1   347058  search_page
2   577020  search_page
3   780347  search_page
4   383739  search_page

   user_id          page
0   253019  payment_page
1   310478  payment_page
2   304081  payment_page
3   901286  payment_page
4   195052  payment_page

   user_id                       page
0   123100  payment_confirmation_page
1   704999  payment_confirmation_page
2   407188  payment_confirmation_page
3   538348  payment_confirmation_page
4   841681  payment_confirmation_page

   user_id        date   device     sex
0   450007  2015-02-28  Desktop  Female
1   756838  2015-01-13  Desktop    Male
2   568983  2015-04-09  Desktop    Male
3   190794  2015-02-18  Desktop  Female
4   537909  2015-01-15  Desktop    Male

### Exporting

In [42]:
home_df.to_csv('clean_home.csv', index=False)
search_df.to_csv('clean_search.csv', index=False)
payment_df.to_csv('clean_payment.csv', index=False)
confirmation_df.to_csv('clean_confirmation.csv', index=False)
user_df.to_csv('clean_users.csv', index=False)

print("Clean CSVs exported.")

Clean CSVs exported.

### Loading tables into MySQL

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:%40Emil@localhost/clara_ecommerce")

pd.read_csv("clean_home.csv").to_sql("clean_home", con=engine, if_exists="replace", index=False)
pd.read_csv("clean_search.csv").to_sql("clean_search", con=engine, if_exists="replace", index=False)
pd.read_csv("clean_payment.csv").to_sql("clean_payment", con=engine, if_exists="replace", index=False)
pd.read_csv("clean_confirmation.csv").to_sql("clean_confirmation", con=engine, if_exists="replace", index=False)
pd.read_csv("clean_users.csv").to_sql("clean_users", con=engine, if_exists="replace", index=False)

print("Data loaded into MySQL successfully.")

# Cleaned data exported and ready for SQL-based analysis in Power BI.
# Any additional transformations were performed directly in the queries.

Data loaded into MySQL successfully.